### ISSUE TITLE
Running node in docker - TypeError: this.stream.clearLine is not a function

### ISSUE THREAD

**Issue by pionl** [sindresorhus/ora#58] opened 2017-09-15 09:59 UTC
Hi,

I'm running my cli command in docker and the ora fails to start. It seems that there is no function in `process.stderr`.

Possible fix is to check the function and return the text per line? (my thought, docker is just streaming the output?).

Thank you for any hints/advices. I can make PR that will check the function.

Martin,

<details>
  <summary>Docker file</summary>

  ```bash
FROM node:8
#... instal etc
# Use the workdir
WORKDIR /usr/src/my-cli

# Install app dependencies
COPY package.json .
COPY package-lock.json .
COPY cli.js .

RUN npm install

RUN npm link
   ```
</details>

<details>
  <summary>Crash</summary>

  ```bash
TypeError: this.stream.clearLine is not a function
    at Ora.clear (/usr/src/my-cli/node_modules/ora/index.js:53:15)
    at Ora.render (/usr/src/my-cli/node_modules/ora/index.js:59:8)
    at Ora.start (/usr/src/my-cli/node_modules/ora/index.js:74:8)
    at Object.<anonymous> (/usr/src/my-cli/cli.js:42:4)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)

   ```
</details>

**Comment by kevva** [comment] 2017-09-15 12:30
How are you using `ora`? Could you share some code? I think `.clearLine` should exist if the stream is a `TTY` which we are checking for here https://github.com/sindresorhus/ora/blob/master/index.js#L34.

**Comment by pionl** [comment] 2017-09-15 14:05
Good point @kevva about setting enabled state. I do set to true. With this I think it should still check the stream object? Unfortunately we loose progress when running the command via docker :)

**Comment by kevva** [comment] 2017-09-16 09:08
Sounds like a duplicate of https://github.com/sindresorhus/ora/issues/9.

If you're forcing a behaviour that isn't supported I don't think we can account for any eventual errors. If you really need it you can just extend `process.stderr` before calling `ora`:

```js
process.stderr.clearLine = () => {};
const spinner = ora('Loading unicorns').start();
```

**Closed by kevva** 2017-09-16 09:08 UTC

**Comment by pionl** [comment] 2017-09-16 09:17
Ok @kevva, I think it's just a point of a view. At this moment there is "enable" option for use case, when user wants to show progress in verbose mode. But there can be env where the progress can't be showed and it should handle this (event enable:true). It should be then called "force".

Thank you for your support/time and have a great day
