### ISSUE TITLE
spin while execSync

### ISSUE THREAD

**Issue by r12r** [sindresorhus/ora#93] opened 2019-01-17 08:59 UTC
Hi! I try to run your beautiful spinner while my script does some execSync calls. But the spinner stops immediately. Any ideas?

Example:

```javascript
const ora = require('ora');
const childProcess = require('child_process');
const spinner = ora().start();
childProcess.execSync('sleep 2');
spinner.stop();
```

**Comment by sindresorhus** [comment] 2019-01-17 09:16
Duplicate of #86

**Closed by sindresorhus** 2019-01-17 09:16 UTC
