### ISSUE TITLE
Indent spinners

### ISSUE THREAD

**Issue by adamsiwiec** [sindresorhus/ora#32] opened 2017-01-08 20:30 UTC
I am wondering how I could indent the spinners so that they are not flush with the left side of the terminal? Seems simple enough but it goes over my head.

**Comment by sindresorhus** [comment] 2017-01-09 07:19
Duplicate of #23. Was implemented in https://github.com/sindresorhus/ora/pull/24, but not finished by the author.

**Closed by sindresorhus** 2017-01-09 07:19 UTC

**Comment by brentonhouse** [comment] 2017-01-09 23:20
@adamsiwiec I have it working in a fork, if you are interested.  I haven't written any tests yet, so it has not been merged with this project.

https://github.com/mobilehero/geek-spinner

**Comment by adamsiwiec** [comment] 2017-01-10 15:00
Ok I will check it out, and maybe right some tests, because this is a must for this package.
