### ISSUE TITLE
if the text is wider than the term every frame is printed on a new line

### ISSUE THREAD

**Issue by dylang** [sindresorhus/ora#7] opened 2016-03-31 00:52 UTC
### Problem

If the text is too long, every frame is printed on a new line, eventually filling up the screen.
### Example

``` js
const ora = require('ora');
const spinner = ora('too long! '.repeat(process.stdout.columns));
spinner.start();
// be prepared to hit control-c a bunch of times
```

<img width="1550" alt="screen shot 2016-03-30 at 8 47 58 pm" src="https://cloud.githubusercontent.com/assets/51505/14162290/bc261d3c-f6b8-11e5-8944-e263cc5dab5d.png">
### Real-world example
- https://github.com/dylang/npm-check/issues/98
### Possible workaround
- Limit text to `process.stdout.columns - 2` (spinner and the space next to the spinner)

**Comment by dylang** [comment] 2016-03-31 19:45
Another possible solution is to support wrapped text. 

I'm not able to check to see if #4 is a possible solution to this issue at this time.

**Comment by daveseco7** [comment] 2017-08-17 18:47
I was trying out the @dylang  work around, where we limit the line size to the size of the `stdout.columns - 2`, thus reserving space for the spinner and white space.
My only concern with this approach is that, if the text of the last action is the oversize one, it will be displayed to the user at the end, otherwise, a user may not read it completely.


The following gif illustrates the result of such implementation, if it's something in line with what you have in mind, I can prepare a PR.
![github](https://user-images.githubusercontent.com/12276728/29427466-c2edfd04-8381-11e7-8e2b-7472409e4f83.gif)

**Comment by sindresorhus** [comment] 2017-08-18 02:21
This could probably be fixed by using [`log-update`](https://github.com/sindresorhus/log-update).

**Comment by daveseco7** [comment] 2017-08-18 22:20
By replacing `stream.write(...)` method calls to `logUpdate(...)` this problem is solved, but once again it may cause some problems. **How to manage streams?**  In _ora_ `stdout` and `stderr` may be specified as an argument, which translates into calling `logUpdate()` or `logUpdate.stderr()` respectively. This also causes tests to fail, since the output may not be read by the test result. (**have not yet confirmed the cause of this issue**).

**Closed** 2018-02-21 16:33 UTC
Labels: bug, help wanted
