### ISSUE TITLE
Why are all the spinners disabled on win32?

### ISSUE THREAD

**Issue by danielgindi** [sindresorhus/ora#62] opened 2017-10-01 13:06 UTC
They work fine for me, if I disable the win32 check...

Thanks :-)

**Comment by sindresorhus** [comment] 2017-10-01 16:16
Duplicate of #40

**Closed by sindresorhus** 2017-10-01 16:16 UTC

**Comment by sindresorhus** [comment] 2017-10-01 16:18
Unicode support in the terminal on Windows is either completely missing, partly supported, and is impossible to detect which reliably, so easier to just do this.

**Comment by pke** [comment] 2019-11-01 00:13
So what's the status on this after 2 years? Do we still have no reliable way of detecting Unicode in the various Windows shells?
