### ISSUE TITLE
spinner corrupted when use Promise.all and each promise has a spinner

### ISSUE THREAD

**Issue by chaoyangnz** [sindresorhus/ora#173] opened 2021-04-30 22:31 UTC
I use a spinner for each promise, and when I run `Promise.all` and hope promises are happening in parallel. 

Ora outputs corrupted texts.

**Comment by sindresorhus** [comment] 2021-05-01 06:46
Duplicate of #116

**Comment by sindresorhus** [comment] 2021-05-01 06:46
Ora currently only supports one spinner at the time.

**Closed by sindresorhus** 2021-05-01 06:46 UTC

**Comment by LaboratorioInternacionalWeb** [comment] 2021-08-03 01:54
You can try: [https://www.npmjs.com/package/multispinners](https://www.npmjs.com/package/multispinners)
